### ISSUE TITLE
Show the total number of packages

### ISSUE THREAD

**Issue by xyb** [hugovk/top-pypi-packages#13]
When it comes to the things that are used the most, the full amount that corresponds is generally displayed. Pypi.org's home page displays the full number of packages in real-time. I thought it would be helpful to show the total number of packages for visitors.

**Comment by hugovk** [comment]
This number isn't part of the data returned in the current query. I'm not sure if it's available via BigQuery, but if it is it'd use more quota, and we're already struggling a bit to stay inside the free quota (eg. see https://github.com/hugovk/top-pypi-packages/issues/6).

And like you say, the real-time data is available at https://pypi.org (currently: 236,007 projects, 1,854,797 releases, 2,852,480 files 425,533 users), so I suggest getting it from there.

But thanks for the suggestion!
