### ISSUE TITLE
Was inspired by the project, made similar, but as a leaderboard, showing the relative dynamics

### ISSUE THREAD

**Issue by ternaus** [hugovk/top-pypi-packages#32]
Was inspired by the project, made similar, but as a leaderboard, showing the relative dynamics

https://pypilb.vercel.app/

**Comment by hugovk** [comment]
Very nice! I've added a link to https://hugovk.github.io/top-pypi-packages/

---

> Data changes between 3/1/2024 and 4/1/2024.

One small suggestion, use a globally unambiguous date format such as "1st March 2024" or "2024-03-01".

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon what would you like to contribute?

@ternaus I noticed it was not updated to the latest release of the data, but you've updated it since so it's all good now 🙂
