### ISSUE TITLE
[Question] How the number of downloads is computed?

### ISSUE THREAD

**Issue by ternaus** [hugovk/top-pypi-packages#34]
If I use link like https://pypistats.org/packages/albumentations numbers look around 10% higher.

I am all for filtering noise from the data, just curious what exactly is filtered.

**Comment by hugovk** [comment]
This repo uses https://github.com/ofek/pypinfo to query BigQuery over the previous 30 days:

https://github.com/hugovk/top-pypi-packages/blob/344411331e24d61307be65cede4facffd84cad5c/generate.sh#L19

pypinfo defaults to only downloads from the pip installer:

https://github.com/ofek/pypinfo/issues/46#issuecomment-388631707

https://pypistats.org/about queries BigQuery directly, so I think includes all installers.

**Comment by ternaus** [comment]
> pypinfo defaults to only downloads from the pip installer:

Thank you. Just to verify, pypinfo just does not count downloads from mirrors?

**Comment by hugovk** [comment]
It's all downloads logged by PyPI. By default, that _does not_ include downloads from mirrors, other clients or ancient pip.

We can check with `installer`:


```console
❯ pypinfo albumentations installer
Served from cache: False
Data processed: 1.05 GiB
Data billed: 1.05 GiB
Estimated cost: $0.01

| installer_name | download_count |
| -------------- | -------------- |
| pip            |      1,902,285 |
```

Checking with all installers:

```console
❯ pypinfo --all albumentations installer
Served from cache: False
Data processed: 1.05 GiB
Data billed: 1.05 GiB
Estimated cost: $0.01

| installer_name | download_count |
| -------------- | -------------- |
| pip            |      1,902,266 |
| uv             |        149,990 |
| poetry         |         31,174 |
| None           |         25,125 |
| requests       |          8,042 |
| bandersnatch   |          2,042 |
| Nexus          |          1,903 |
| pdm            |          1,428 |
| Browser        |          1,023 |
| Bazel          |            449 |
| Total          |      2,123,442 |
```

**Comment by ternaus** [comment]
Got it, thanks. This is very helpful. Will update the description at https://pypilb.vercel.app/
