### ISSUE TITLE
being used by Top pytest Plugins

### ISSUE THREAD

**Issue by okken** [hugovk/top-pypi-packages#37]
List: https://pythontest.com/top-pytest-plugins/
Blog post about it: https://pythontest.com/pytest/finding-top-pytest-plugins/
Source code: https://github.com/okken/top-pytest-plugins

I'm manually updating currently, but plan on trying to figure out the updates.
I think I might try to figure out if cron in GH Actions works ok.

**Comment by hugovk** [comment]
GitHub Actions is a good choice, see for example:

* https://github.com/hugovk/free-threaded-wheels/blob/main/.github/workflows/deploy.yml
* https://github.com/di/pyreadiness/blob/master/.github/workflows/cron.yml

Keep in mind:

> * In a public repository, scheduled workflows are automatically disabled when no repository activity has occurred in 60 days. For information on re-enabling a disabled workflow, see "Disabling and enabling a workflow."

https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule

Stuff like dependabot and pre-commit.ci can help keep things active. I've even seen one repo that had a cron to make dummy commits to a branch just to keep the repo active!

**Comment by hugovk** [comment]
Thanks, added in https://github.com/hugovk/top-pypi-packages/commit/6121a37584598a78e4b5718ddb04a712aefbac83!
